version: '3.8'
services:
  db:
    image: postgres:17-alpine
    container_name: resto-postgres
    restart: always
    environment:
      POSTGRES_USER: resto_user
      POSTGRES_PASSWORD: resto_password
      POSTGRES_DB: resto_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: